<?php
// Get the party planner product collection.
$_productCollection = $this->getPartyPlannerProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
 <div class="ppbg-img">
 	<div class="desktop" ><img src="<?php echo $this->getSkinUrl('images/bkg_party_planner.png') ?>" alt="Party Planner" /></div>
    </div>
    <div class="category-products">
   
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = 6; ?>
        <?php $i = 0;
        foreach ($_productCollection as $_product): ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                <ul class="products-grid">
        <?php endif ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
<?php endif; ?>