<?php
// Get the config setting.
$_configSettings = $this->helper('zeon_catalogmanager')->getConfigDetails('featured_products');
if ($_configSettings['active']):
    // Get the featured product collection.
    $_productCollection = $this->getFeaturedProductCollection();
    //Get inactive categories
    $inActiveCategories = Mage::helper('zeon_catalogmanager')->getInActiveCategories();

    if ($_productCollection && $_productCollection->count()):
        // Get the catalog helper.
        $_helper = $this->helper('catalog/output');
        $_catalogBlock = Mage::getBlockSingleton('catalog/product_list');

        $_maxCharLimit = (int) $_configSettings['char_limit'];
        $_columnCount = ((int) $_configSettings['number_of_items_per_row'] > 0) ? $_configSettings['number_of_items_per_row'] : $this->getColumnCount();
?>
    <div class="category-products featured-item">
            <div class="green-title-sec">
                <span class="green-title"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>catalog-manager/index/"><?php echo $this->__('Featured Items'); ?></a></span>
                </div>
    <?php
    $_collectionSize = $_productCollection->count();
    $i = 0;
    foreach ($_productCollection as $_product):
        // Loop on till max number of item setting.
        if ($i+1 > $_configSettings['number_of_items']):
            break;
        endif;

        // Get the product categories and get the last one to display details.
        $categories  = $_product->getCategoryIds();
        foreach ($inActiveCategories as $falseCat) {
            if(($key = array_search($falseCat, $categories)) !== false) {
                unset($categories[$key]);
            }
        }
        $_categoryId = end($categories);
        $_category   = Mage::getModel('catalog/category')->load($_categoryId);
    ?>
    <?php if ($i++ % $_columnCount == 0): ?>
        <ul class="products-grid">
    <?php endif ?>
            <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?> col-lg-3 col-sm-3 col-xs-6">
                <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true); ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                </a>
                <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                        <?php echo ($_maxCharLimit > 0 && strlen($_productName) > $_maxCharLimit) ? substr($_productName, 0, $_maxCharLimit) . '...' : $_productName; ?>
                    </a>
                </h2>
                <?php //if ($_product->getRatingSummary()): ?>
                    <?php echo $_catalogBlock->getReviewsSummaryHtml($_product, 'short') ?>
                <?php //endif; ?>

                <?php if ($_configSettings['price_visible']): ?>
                    <?php echo $_catalogBlock->getPriceHtml($_product, true) ?>
                <?php endif; ?>
            </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
            </ul>
            <?php endif ?>
    <?php endforeach ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
<?php
    endif;
endif;
?>
