<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>
<?php $helper = Mage::helper('zeon_googletagmanager'); ?>
<?php $_order = $this->getOrder(); ?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head"><h4 class="icon-head head-account">
                <?php echo $helper->__('Visitor Information') ?></h4></div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo $helper->__('Customer Name') ?></label></td>
                    <td class="value">
                        <?php if ($_customerUrl = $this->getCustomerViewUrl()) : ?>
                            <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                        <?php else: ?>
                            <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Email') ?></label></td>
                    <td class="value"><strong><?php echo $_order->getCustomerEmail() ?></strong></td>
                </tr>
                <?php if ($_order->getRemoteIp()): ?>
                    <tr>
                        <td class="label"><label><?php echo $helper->__('Placed from IP') ?></label></td>
                        <td class="value"><strong><?php
                echo $_order->getRemoteIp();
                echo ($_order->getXForwardedFor()) ? ' (' . $this->escapeHtml($_order->getXForwardedFor()) . ')' : '';
                    ?></strong></td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Unique Identifier') ?></label></td>
                    <td class="value"><strong><?php echo $this->getUniqueIdentifier() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('First Visit') ?></label></td>
                    <td class="value"><strong><?php echo $this->getFirstVisit() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Previous Visit') ?></label></td>
                    <td class="value"><strong><?php echo $this->getPreviousVisit() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Current Visit') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCurrentVisit() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Number of Sessions') ?></label></td>
                    <td class="value"><strong><?php echo $this->getNoOfSessions() ?></strong></td>
                </tr>
            </table>
        </div>
        <div class="entry-edit-head"><h4 class="icon-head head-account">
                <?php echo $helper->__('Sessions Tracking') ?></h4></div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo $helper->__('Number of page views in current session') ?></label></td>
                    <td class="value"><strong><?php echo $this->getPageViewed() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Timestamps of current session time') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCurrentSessionTime() ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head"><h4 class="icon-head head-account">
                <?php echo $helper->__('Traffic sources') ?></h4></div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo $helper->__('Timestamp when cookie was set') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCookieTime() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Session Number') ?></label></td>
                    <td class="value"><strong><?php echo $this->getSessionNumber() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Campaign Number') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCampaignNumber() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Campaign Source') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCampaignSource() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Campaign Name') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCampaignName() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Campaign Medium') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCampaignMedium() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $helper->__('Keyword used to enter in site') ?></label></td>
                    <td class="value"><strong><?php echo $this->getCampaignKeyword() ?></strong></td>
                </tr>
                <tr>
                    <td class="label" colspan="2"></td>
                </tr>
                <tr>
                    <td class="label" colspan="2"></td>
                </tr>
                <tr>
                    <td class="label" colspan="2"></td>
                </tr>
            </table>
        </div>
        <div class="entry-edit-head"><h4 class="icon-head head-account">
                <?php echo $helper->__('Custom Value & Additional Cookies') ?></h4></div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php
                $customValues = $this->getCustomValues();
                if (count($customValues) > 0):
                    foreach ($customValues as $cLbl => $cValue) :
                        ?>
                        <tr>
                            <td class="label"><label><?php echo $helper->__($cLbl) ?></label></td>
                            <td class="value"><strong><?php echo $cValue ?></strong></td>
                        </tr>
                        <?php
                    endforeach;
                endif;
                ?>
            </table>
        </div>
    </div>
</div>