<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>

<?php if ($this->getItems()->getSize()): ?>
    <div class="box-collateral box-related">
        <div class="box-title">
            <strong><span><?php echo $this->__('Related Products') ?></span></strong>
        </div>
        <p class="note"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><strong><?php echo $this->__('select all') ?></strong></a></p>
        <?php $i = 0;
        foreach ($this->getItems() as $_item): ?>
                <?php if ($i++ % 3 == 0): ?>
                <ul class="block-content">
                    <?php endif ?>
                <li class="item<?php if (($i - 1) % 3 == 0): ?> first<?php elseif ($i % 3 == 0): ?> last<?php endif; ?>">
                    <?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                        <?php endif; ?>
        <?php endif; ?>
                    <div class="item-info">
                        <a href="<?php echo $_item->getProductUrl() ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(100) ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                        <div class="product-details">
                            <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                            <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <p><a href="javascript:void(0);" onclick="ajaxCart.addByUrl('<?php echo $this->getAddToWishlistUrl($_item) ?>', <?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/whishlist_enabled') ? 'true' : 'false'; ?>); return false;"><?php echo $this->__('Add to Wishlist') ?></a></p>
        <?php endif; ?>
                        </div>
                    </div>
                </li>
            <?php if ($i % 3 == 0 || $i == $this->getItems()->count()): ?>
                </ul>
            <?php endif ?>
    <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('.box-related ul.block-content'), ['odd','even','first','last'])</script>

        <script type="text/javascript">
            //<![CDATA[
            $$('.related-checkbox').each(function(elem){
                Event.observe(elem, 'click', addRelatedToProduct)
            });
        
            var relatedProductsCheckFlag = false;
            function selectAllRelated(txt){
                if (relatedProductsCheckFlag == false) {
                    $$('.related-checkbox').each(function(elem){
                        elem.checked = true;
                    });
                    relatedProductsCheckFlag = true;
                    txt.innerHTML="<strong><?php echo $this->__('unselect all') ?><\/strong>";
                } else {
                    $$('.related-checkbox').each(function(elem){
                        elem.checked = false;
                    });
                    relatedProductsCheckFlag = false;
                    txt.innerHTML="<strong><?php echo $this->__('select all') ?><\/strong>";
                }
                addRelatedToProduct();
            }
        
            function addRelatedToProduct(){
                var checkboxes = $$('.related-checkbox');
                var values = [];
                for(var i=0;i<checkboxes.length;i++){
                    if(checkboxes[i].checked) values.push(checkboxes[i].value);
                }
                if($('related-products-field')){
                    $('related-products-field').value = values.join(',');
                }
            }
            //]]>
        </script>
    </div>
    <?php
 endif ?>
