<?php return; ?>
<table class="form-list">
	<tr>
		<td class="scope-label">
			<button onclick="setLocation('<?php echo $this->getFlushCacheUrl()?>')" type="button" class="scalable"><span><?php echo $this->__('Flush Optimized Image Cache') ?></span></button>
		</td>
		<td class="scope-label">
			<?php echo $this->__('Extendware optimized images caches (usually no need to flush).')?>
		</td>
	</tr>
</table>
