<?php
/**
 *
 *
 * @author Ashley Schroder (aschroder.com)
 * @copyright  Copyright (c) 2013 ASchroder Consulting Ltd
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php

// To ensure the graph looks sensible even for low numbers
$maxSends = 10;
$maxOther = 10;

?>

<?php if($emailData = Mage::registry('email_data')): ?>

    <div id="visualization" style="width: 900px; margin: 0px auto 20px; border: 1px solid #ccc;">
    </div>


    <script type="text/javascript" src="//www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load('visualization', '1', {packages: ['corechart']});
    </script>
    <script type="text/javascript">

        function drawVisualization() {
            // Create and populate the data table.
            var data = google.visualization.arrayToDataTable([
                ['Day', 'Emails Sent', 'Rejects', 'Bounces', 'Complaints'],
                <?php foreach ($emailData as $date => $emails): ?>
                    <?php $maxSends = max($maxSends, $emails["sends"]); ?>
                    <?php $maxOther = max($maxOther, $emails["rejects"], $emails["bounces"], $emails["comps"]); ?>
                    ["<?php echo $date ?>",<?php echo $emails["sends"] ?>,<?php echo $emails["rejects"] ?>,<?php echo $emails["bounces"] ?>,<?php echo $emails["comps"] ?>],
                <?php endforeach ?>
            ]);

            // Create and draw the visualization.
            var ac = new google.visualization.ComboChart(document.getElementById('visualization'));
            ac.draw(data, {
                    width: 900,
                    height: 600,
                    vAxes: {0: {title: "Emails Sent", logScale: false, maxValue: <?php echo $maxSends ?>, minValue: 0},
                        1: {title: "Problem Emails", logScale: false, maxValue: <?php echo $maxOther ?>, minValue: 0}},
                    hAxis: {title: "Day"},
                    seriesType: "bars",
                    series:{
                        0:{targetAxisIndex:0},
                        1:{targetAxisIndex:1},
                        2:{targetAxisIndex:1},
                        3:{targetAxisIndex:1}}}
            );
        }
        google.setOnLoadCallback(drawVisualization);
    </script>
<?php endif; ?>