<?php
/**
 * 
 * @category   CRM4Ecommerce
 * @package    CRM4Ecommerce_CRMCore
 * @author     Philip Nguyen <philip@crm4ecommerce.com>
 * @link       http://crm4ecommerce.com
 * @see        CRM4Ecommerce_CRMCore_Block_Adminhtml_Config_Html_Form_Support
 */
?>
<script type="text/javascript" src="http://assets.freshdesk.com/widget/freshwidget.js"></script>
<style type="text/css" media="screen, projection">
    @import url(http://assets.freshdesk.com/widget/freshwidget.css);
</style> 
<iframe class="freshwidget-embedded-form" id="freshwidget-embedded-form" src="http://crm4ecommercecom.freshdesk.com/widgets/feedback_widget/new?&widgetType=embedded&screenshot=no" scrolling="no" height="800px" width="100%" frameborder="0" >
</iframe>