
<div id="braintree_paypal_logo" style="padding-top: 5px;padding-left: 2px;">
    <img src="//i.imgur.com/sitDbHA.png" alt="<?php echo $this->__('PayPal - Braintree'); ?>" /> by <a href="http://gene.co.uk" target="_blank" style="text-decoration: none;">Gene Commerce</a>
</div>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <tr>
                <th width="180"><?php echo $this->escapeHtml($_label)?>:</td>
                <td><?php echo nl2br(implode($this->getValueAsArray($_value, false), "\n"))?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
