<?php
/**
 * @category    Fqs
 * @package     Fqs_Attributemapping
 * @@copyright   Copyright (c) 2012 Zeon Solutions, Inc. All Rights Reserved.(http://www.zeonsolutions.com)
 * @license     http://www.zeonsolutions.com/license/
 */
?>
<div class="page-title category-title">
    <h1><?php echo ($this->getHeaderText() || $this->getHeaderText() === false) ? $this->getHeaderText() : $this->__("Search results for '%s'", $this->helper('catalogsearch')->getEscapedQueryText()) ?></h1>
    <div class="filter-col-block browser-cat">
        <span class="title">Browser Categories</span>
        <div class="filter-icon">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</div>
