<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>

<div id="loading-mask" style="display:none;">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/zeon/ajaxcart/ajax-loader.gif') ?>" alt="<?php echo Mage::helper('zeon_ajaxcart')->__('Loading...') ?>" /><br /><?php echo Mage::helper('zeon_ajaxcart')->__('Please wait...') ?></p>
</div>
<script type="text/javascript">
    var ajaxCart = new AjaxCart();
    function validateOptionsCallback(elmId, result){
        var container = $(elmId).up('ul.options-list');
        if (result == 'failed') {
            container.removeClassName('validation-passed');
            container.addClassName('validation-failed');
			
        } else {
            container.removeClassName('validation-failed');
            container.addClassName('validation-passed');
			
        }
    }
</script>