<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<?php if ($this->isEnableProductPayments()) : ?>

<div id="<?php echo $this->getAmazonPayButtonId(); ?>"></div>
<script type="text/javascript">
  var authRequest;

  var AmazonButtonOptions = {
      type: "<?php echo ($this->isAmazonLoginEnabled()) ? 'LwA' : $this->getButtonType(); ?>",
      color: "<?php echo $this->getButtonColor(); ?>",
      size: "<?php echo $this->getButtonSize(); ?>",
      authorization: function() {
          loginOptions = {
              scope: "profile payments:widget payments:shipping_address<?php print $this->getAdditionalScope(); ?>"
          };

          authRequest = amazon.Login.authorize (loginOptions, "<?php echo $this->getOnepageCheckoutUrl(); ?>");
      },
      onError: function(error) {
          console.log(error);
      }
  };

  OffAmazonPayments.Button("<?php echo $this->getAmazonPayButtonId(); ?>", "<?php echo $this->getSellerId(); ?>", AmazonButtonOptions);
</script>

<br />
<p class="amazon-or-sep"><strong><?php echo $this->__('OR'); ?></strong></p>

<?php endif; ?>