<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('<span class="mobile-hide">Your</span> Shopping Cart') ?></h1>
        <?php/* if (!$this->hasError()): ?>
            <ul class="checkout-types">
                <?php foreach ($this->getMethods('top_methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; */?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <div class="allItemCount"><?php echo count($this->getItems()); ?> <?php echo $this->__('Item(s)');?></div>
    <form id="product_updatecart_form" action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" onsubmit="ajaxCart.updateCart('<?php echo $this->getUrl('checkout/cart/updatePost') ?>', <?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/cart_enabled') ? 'true' : 'false'; ?>);return false">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col />
                <col width="1" />
                <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                    <col width="1" />
                <?php endif ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <col width="1" />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <col width="1" />

                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Item Description') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="item-desc">&nbsp;</th>
                        <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Price') ?></span></th>
                        <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                        <?php endif*/ ?>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty.') ?></th>
                        <th class="a-right" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Total') ?></th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <tr>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        </tr>
                    <?php endif; ?>
                </thead>
                <tbody>
                    <?php foreach ($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            <script type="text/javascript">
                function emptyCart() {
                    $('clear_cart_action').setValue('empty_cart');
                    ajaxCart.updateCart('<?php echo $this->getUrl('checkout/cart/updatePost') ?>', <?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/cart_enabled') ? 'true' : 'false'; ?>);
                }

                function moveToWishlist(listUrl,thisObj) {
                    var url = jQuery(thisObj).attr('href');
                    var wishlistId = getallurl('wishlist_id', url);
                    ajaxCart.addUpdateWishlistFromCart(listUrl, wishlistId);
                }
            </script>
        </fieldset>
    </form>
    <div class="deals">
        <div class="left col-lg-7 col-md-7 col-sm-6 col-xs-12">
            <?php echo $this->getChildHtml('coupon') ?>
            <?php echo $this->getChildHtml('giftcards') ?>
        </div>
        <div class="donation-box col-lg-5 col-md-5 col-sm-6 col-xs-12">
            <?php echo $this->getChildHtml('donation_block') ?>
        </div>
    </div>

    <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>

    <div class="totals">
        <?php echo $this->getChildHtml('totals'); ?>
    </div>

    <?php if(!$this->hasError()): ?>
    <ul class="checkout-types">
    <?php foreach ($this->getMethods('methods') as $method): ?>
        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
        <li><?php echo $methodHtml; ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
    <?php if($this->getContinueShoppingUrl()): ?>
        <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    <?php endif; ?>
</div>
