<?php
/**
 * Include the crucial braintree-data.js for fraud protection
 */
?>
<script src="https://js.braintreegateway.com/v1/braintree-data.js"></script>
<script type="text/javascript">

    // Only include the setup call once
    if(braintreeDataEnv === undefined) {

        <?php if($kountId = Mage::getStoreConfig('payment/gene_braintree_creditcard/kount_merchant_id')): ?>
        var braintreeDataEnv = BraintreeData.environments.production.withId("<?php echo $kountId; ?>");
        <?php else: ?>
        var braintreeDataEnv = BraintreeData.environments.<?php echo Mage::getStoreConfig(Gene_Braintree_Model_Wrapper_Braintree::BRAINTREE_ENVIRONMENT_PATH); ?>;
        <?php endif; ?>
        BraintreeData.setup("<?php echo Mage::getStoreConfig(Gene_Braintree_Model_Wrapper_Braintree::BRAINTREE_MERCHANT_ID_PATH); ?>", '<?php echo ($this->getPaymentFormId() ? $this->getPaymentFormId() : 'co-payment-form'); ?>', braintreeDataEnv);

        // Update the device_data's field name to contain payment
        if ($('device_data')) {
            $('device_data').setAttribute('name', 'payment[device_data]');
        }
    }
</script>

