<?php
/**
 * Add in support for Fire Checkout
 * http://templates-master.com/magento-one-page-checkout.html
 * @author Dave Macaulay <dave@gene.co.uk>
 */
?>
<!-- FIRECHECKOUT BRAINTREE SUPPORT -->
<script type="text/javascript">

    vZeroIntegration.addMethods({

        /**
         * Validate the entire checkout
         */
        validateAll: function() {
            return checkout.validate();
        },

        /**
         * Attach an observer to the submit action of the checkout to tokenize the card details
         */
        prepareSubmitObserver: function() {

            // Store a pointer to the vZero integration
            var vzeroIntegration = this;

            // Store the old complete checkout function
            var _originalSave = FireCheckout.prototype.save;

            // Re-define the original method so we can do some jazz with it
            FireCheckout.prototype.save = function () {

                if (vzeroIntegration.shouldInterceptSubmit('creditcard')) {

                    // Store a pointer to the payment class
                    var paymentThis = this;
                    var paymentArguments = arguments;

                    // If everything was a success on the checkout end, let's submit the vZero integration
                    vzeroIntegration.submit('creditcard', function () {
                        return _originalSave.apply(paymentThis, paymentArguments);
                    });

                } else {
                    // If not run the original code
                    return _originalSave.apply(this, arguments);
                }

            };

        },

        /**
         * The action to run after the PayPal action has been completed
         */
        submitCheckout: function() {
            // Run the original checkouts submit action
            return checkout.save();
        },

        /**
         * Override the loading function to set the counter to 0 so the loader actually gets hidden
         */
        resetLoading: function() {
            checkout.loadCounter=0;
            checkout.setLoadWaiting(false);
        }

    });

    /**
     * Start a new instance of our integration
     *
     * @type {vZeroIntegration}
     */
    new vZeroIntegration(
        (window.vzero || false),
        (window.vzeroPaypal || false),
        '<div id="paypal-complete"><div id="paypal-container"></div></div>',
        '#review-buttons-container .btn-checkout',
        true,
        {
            ignoreAjax: ['firecheckout/index/saveOrder']
        }
    );

</script>