<?php
/**
 * Setup the JavaScript classes with their required fields
 */
/* @var $this Gene_Braintree_Block_Js */
?>
<script type="text/javascript">

    // Only init the vzero class once
    if(vzero === undefined) {

        // Pass some data over to vZero integration JS
        var vzero = new vZero(
            'gene_braintree_creditcard',
            '<?php echo $this->getClientToken(); ?>',
            <?php echo $this->is3DEnabled(); ?>,
            <?php echo $this->isHostedFields(); ?>,
            false,
            false,
            '<?php echo Mage::getUrl('braintree/checkout/quoteTotal', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>',
            '<?php echo Mage::getUrl('braintree/checkout/tokenizeCard', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>',
            '<?php echo Mage::getUrl('braintree/checkout/vaultToNonce', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>'
        );

        <?php if($this->isPayPalActive()): ?>
        // Pass some data through to the PayPal integration
        var vzeroPaypal = new vZeroPayPalButton(
            '<?php echo $this->getClientToken(); ?>',
            '<?php echo Mage::app()->getStore()->getFrontendName(); ?>',
            <?php echo $this->getSingleUse(); ?>,
            '<?php echo $this->getLocale(); ?>',
            <?php echo $this->getSingleFutureUse(); ?>
        );
        <?php endif; ?>

        // Init the environment
        vzero.init();

    }

</script>

<script type="text/html" id="braintree-paypal-button">
    <button type="button" name="braintree-paypal-button" class="braintree-paypal-button">
        <span>
            <span>
                <?php echo $this->__('Checkout with'); ?>
            </span>
        </span>
    </button>
</script>

<?php
/**
 * We always want to hide the logged in aspect of the PayPal button, only ever display the button
 */
?>
<style type="text/css">
    #braintree-paypal-loggedin {
        display: none!important;
    }
    #braintree-paypal-loggedout {
        display: block!important;
    }
</style>