<?php
/**
 * @category    design
 * @package     zeon_ajaxaddtocart
 * @copyright   Copyright (c) 2013 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://www.magentocommerce.com/license/enterprise-edition
 */
?>
<?php
/* @var $this Enterprise_Wishlist_Block_Customer_Wishlist_Management */
?>
<?php if ($this->getCurrentWishlist()): ?>
<div class="wishlist-management ">
    <div class="my-wishlist-header">
    <div class="label"><?php echo $this->__('Wishlist:'); ?></div>
    <div class="table-caption">
        <div id="wishlists-select" class="split-button">
            <strong><span title="<?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?>"><?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?></span></strong>
            <a href="#" onclick="Enterprise.Wishlist.edit('<?php echo $this->getEditUrl($this->getCurrentWishlist()->getId());?>', '<?php echo $this->helper('core')->quoteEscape($this->getCurrentWishlist()->getName(), true);?>', <?php echo $this->getCurrentWishlist()->getVisibility() ? 'true' : 'false';?>); createCustomCheckboxesAndRadio();" title="<?php echo $this->__('Edit Wishlist')?>" class="link-edit wishlist-edit">&nbsp;</a>
            <a class="change" href="#">(<span><?php echo $this->__('Change') ?></span>)</a>
            <div class="list-container">
                <ul>
                    <?php foreach($this->getWishlists() as $wishlist): ?>
                        <?php if ($wishlist->getId() != $this->getCurrentWishlist()->getId()): ?>
                            <li><a title="<?php echo $this->escapeHtml($wishlist->getName());?>" href="<?php echo $this->getUrl('wishlist/index/index', array('wishlist_id' => $wishlist->getId()));?>"><?php echo $this->escapeHtml($wishlist->getName());?></a></li>
                        <?php endif; ?>
                    <?php endforeach;?>
                    <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                        <li class="create-new-wish" onclick="Enterprise.Wishlist.create('<?php echo $this->getCreateUrl();?>'); createCustomCheckboxesAndRadio();"><span title="<?php echo $this->__('Create New Wishlist')?>"><?php echo $this->__('Create New Wishlist')?></span></li>
                    <?php endif;?>
                </ul>
            </div>
        </div>
    </div>
    <div class="wishlist-count">
        <?php echo $this->__('%d item(s)', $this->getItemCount($this->getCurrentWishlist())); ?>
    </div>

    <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
        <button type="button" id="wishlist-create-button" onclick="Enterprise.Wishlist.create('<?php echo $this->getCreateUrl();?>'); createCustomCheckboxesAndRadio();" title="<?php echo $this->__('Create New Wishlist') ?>" class="button btn-create right red-button"><span><span><?php echo $this->__('Create New Wishlist') ?></span></span></button>
    <?php endif;?>

    </div>
     <?php if ($this->getCurrentWishlist()->getVisibility()): ?>
        <p class="note-msg msg-public"><?php echo $this->__('This wishlist is publicly visible.'); ?></p>
        <?php else: ?>
        <p class="note-msg msg-private"><?php echo $this->__('This wishlist is private. Only you can view this wishlist.');?></p>
    <?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
        Enterprise.Wishlist.form = $('wishlist-view-form');
        if (!Enterprise.Wishlist.url) {
            Enterprise.Wishlist.url = {};
        }

        Enterprise.Wishlist.url.EnableAjax = true;
        Enterprise.Wishlist.url.copySelected = '<?php echo $this->getCopySelectedUrl();?>';
        Enterprise.Wishlist.url.moveSelected = '<?php echo $this->getMoveSelectedUrl();?>';
        Enterprise.Wishlist.url.copyItem = '<?php echo $this->getCopyItemUrl();?>';
        Enterprise.Wishlist.url.moveItem = '<?php echo $this->getMoveItemUrl();?>';
    //]]>
    </script>
</div>
<?php endif; ?>




