<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<div id="amazon-checkout">

    <div class="page-title">
        <h1><?php echo $this->__('Checkout') ?></h1>
    </div>

    <?php echo $this->__('Amazon Payments uses information from your Amazon account to place your order.'); ?>
    <?php echo $this->__('Click <a href="#" id="amazon-cancel">here</a> to change your payment method.'); ?>


    <div id="checkout-amazon-payments">
        <div id="checkout-amazon-columns">

            <div id="col-1-amz" class="col-amz">

                <div id="amazon-widget-address-wrapper" class="amazon-widget-wrapper">
                    <h2><?php echo $this->__('Shipping Address'); ?></h2>
                    <div id="amazon-widget-address"></div>
                </div>

                <?php if ($this->getChild('shipping_method')->isShow()) : ?>
                    <div id="shipping-method-wrapper">
                        <?php echo $this->getChildHtml('shipping_method') ?>
                    </div>
                <?php endif; ?>

            </div>

            <div id="col-2-amz" class="col-amz">

                <div id="amazon-widget-wrapper" class="amazon-widget-wrapper">
                    <h2><?php echo $this->__('Payment'); ?></h2>
                    <div id="amazon-widget-wallet"></div>
                </div>

            </div>


            <div id="col-3-amz" class="col-amz">
                <h2><?php echo $this->__('Order Summary'); ?></h2>

                <div id="amz-review-loader" style="display:none;"></div>

                <?php echo $this->getChildHtml('review') ?>

                <?php if ($this->helper('amazon_payments')->isAmazonSandbox()) : ?>
                <br />
                <h3>Authorization Sandbox Simulation:</h3>
                <textarea id="sandbox"></textarea>
                Example:
                <small>
                 	{"SandboxSimulation": {"State":"Declined", "ReasonCode":"InvalidPaymentMethod"}}
                  <br />
                  (<a href="http://docs.developer.amazonservices.com/en_US/apa_guide/APAGuide_Testing.html" target="_blank">More Info</a>)<br />
                </small>


                <?php endif; ?>
            </div>

        </div>
    </div>

</div>

<script>

// Cancel and log user out of Amazon
$('amazon-cancel').observe("click", function() {
  amazon.Login.logout();
  window.top.location.href = "<?php echo $this->getUrl('amazon_payments/checkout/clear'); ?>";
});


var AmazonPaymentsMageCheckout = Class.create();
AmazonPaymentsMageCheckout.prototype = {
    initialize: function(opts){
        this.opts = opts;
        //this.setShippingMethod();
    },

    // Dynamically load shipping method HTML
    setShippingMethod: function() {
        if (this.opts.shippingMethod) {
            this.toggleOrderSubmit(true);

            var request = new Ajax.Request(this.opts.shippingMethod.url, {
                method: 'post',
                parameters: { "amazon_order_reference_id": this.amazonOrderReferenceId },
                onSuccess: this.renderShippingMethod.bindAsEventListener(this, this.opts.shippingMethod.id)
            });
        }
        else {
            this.setReview();
        }
    },

    // Dynamically load review HTML
    setReview: function() {
        var btnSubmit = $$(".button.btn-checkout");

        var shippingMethod = $$('input:checked[type=radio][name=shipping_method]')[0];

        if (shippingMethod != undefined) {
            shippingMethod = shippingMethod.value;
        }
        else {
            var firstMethodRadio = $$('input[type=radio][name=shipping_method]').first();
            if (firstMethodRadio != undefined) {
                firstMethodRadio.checked = "checked";
                shippingMethod = firstMethodRadio.value;
            }
        }

        this.toggleOrderSubmit(true);

        var request = new Ajax.Request(this.opts.review.url, {
            method: 'post',
            parameters: { "shipping_method": shippingMethod, "amazon_order_reference_id": this.amazonOrderReferenceId },
            onSuccess: this.renderReview.bindAsEventListener(this, this.opts.review.id)
        });
    },

    // Render shipping method, then load Review
    renderShippingMethod: function(transport, id) {
        $(id).update(transport.responseText);

        $$('input[type="radio"][name="shipping_method"]').each(function(el){
            Event.observe(el, 'change', this.setReview.bindAsEventListener(this));
       }, this);

       this.setReview();
    },

    renderReview: function(transport, id) {
        $(id).update(transport.responseText);
        $$(".button.btn-checkout").invoke('writeAttribute','onclick', 'amazonPaymentsMageCheckout.saveOrder()');
        this.agreementsForm = $('checkout-agreements')
        $("amz-review-loader").hide();
    },

    saveOrder: function() {
      var params = {};

      if (this.agreementsForm) {
          params += '&'+Form.serialize(this.agreementsForm);
      }
      params.save = true;

      params.amazon_order_reference_id = this.amazonOrderReferenceId;

      var sandbox = $('sandbox');
      if (sandbox) {
          params.sandbox = sandbox.getValue();
      }

      this.toggleOrderSubmit(true);

      var request = new Ajax.Request(this.opts.save.url, {
          method: 'post',
          parameters: params,
          onSuccess: this.onSaveOrder.bindAsEventListener(this)
      });
    },

    onSaveOrder: function(transport) {
        try{
            response = eval('(' + transport.responseText + ')');
        }
        catch (e) {
            response = {};
        }

        if (response.redirect) {
            this.isSuccess = true;
            amazon.Login.logout();//custom code added for logout session
            window.top.location.href = response.redirect;
            return;
        }
        if (response.success) {
            this.isSuccess = true;
            amazon.Login.logout();//custom code added for logout session
            window.top.location.href = this.successUrl;
        }
        else{
            var msg = response.error_messages;
            if (typeof(msg)=='object') {
                msg = msg.join("\n");
            }
            if (msg) {
                alert(msg);
            }

            // Widget reload requried
            if (msg.indexOf("TransactionTimedOut") != -1) {
                location.reload();
            }
            else if (msg.indexOf("terms and conditions") == -1) {
                setTimeout(loadAmazonWallet, 2000); // Refresh Wallet
            }

        }

        this.toggleOrderSubmit(false);
    },

    toggleOrderSubmit: function(isDisabled) {
        var btn = $$(".button.btn-checkout");
        var review = $("checkout-review-table-wrapper");
        var loader = $("amz-review-loader");

        if (isDisabled) {
            if (review) {
                review.setOpacity(0.5);
                loader.show();
            }
            btn.invoke('writeAttribute','disabled','disabled');
        } else {
            if (review) {
                review.setOpacity(1);
                loader.hide();
            }

            btn.invoke('removeAttribute','disabled');
        }
    }
};

var opts = {
  <?php if ($this->getChild('shipping_method')->isShow()) : ?>
  shippingMethod : {
      id: "checkout-shipping-method-load",
      url: "<?php echo $this->getUrl('checkout/amazon_payments/shippingMethod') ?>"
  },
  <?php endif; ?>
  review : {
      id: "checkout-review-load",
      url: "<?php echo $this->getUrl('checkout/amazon_payments/review') ?>"
  },
  save : {
      url: "<?php echo $this->getUrl('checkout/amazon_payments/saveOrder') ?>"
  }
}


var amazonPaymentsMageCheckout = new AmazonPaymentsMageCheckout(opts);


// Variables/objects for Mage Onepage
var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
var lastPrice;

var ShippingMethod = Class.create();
var Review = Class.create();


</script>


<!-- Address Book Widget JS -->
<script>

new OffAmazonPayments.Widgets.AddressBook({
  sellerId: '<?php echo $this->getSellerId(); ?>',
  onOrderReferenceCreate: function(orderReference) {
      amazonPaymentsMageCheckout.amazonOrderReferenceId = orderReference.getAmazonOrderReferenceId();
  },
  onAddressSelect: function(orderReference) {
      amazonPaymentsMageCheckout.setShippingMethod();
  },
  design: {
     designMode: 'responsive'
  },
  onError: function(error) {
    if (error.getErrorCode() == "BuyerSessionExpired") {
         window.top.location.href = '<?php echo $this->getUrl('checkout/amazon_payments/clear'); ?>';
    }
    console.log(error.getErrorMessage());
  }
}).bind("amazon-widget-address");
</script>


<!-- Wallet Widget JS -->
<script>
function loadAmazonWallet() {
    new OffAmazonPayments.Widgets.Wallet({
      sellerId: '<?php echo $this->getSellerId(); ?>',
        design: {
          designMode: 'responsive',
      },

      onPaymentSelect: function(orderReference) {

      },
      onError: function(error) {
        console.log(error.getErrorMessage());
      }
    }).bind("amazon-widget-wallet");
}

loadAmazonWallet();
</script>
