<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
/* @var $this Mage_Catalog_Block_Layer_State */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<?php
    $optionId  = $this->getRequest()->getParam('id', 0);
    $codeData = $this->getRequest()->getParam('attribute_name', 0);
    $filterArray = array();
    if (isset($_filter)) {
        echo $this->getActivefilterCode($_filter);
    }
    foreach ($_filters as $_filter):
        if (Mage::app()->getRequest()->getModuleName() != 'attribute') {
            if ($_filter->getValue() != $optionId) :
                $filterArray[] = $_filter;
            endif;
        }
    endforeach;
    ?>
<?php if (Mage::helper('mana_core')->isMageVersionEqualOrGreater('1.7') && !empty($filterArray)) : ?>
    <div class="actions"><span><?php echo $this->__('Your Selections') ?></span><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
<?php endif; ?>
<div class="currently">
    <?php if (!empty($filterArray)) : ?>
    <ol>
    <?php foreach ($filterArray as $_filter): ?>
    <?php if ($_html = $this->getValueHtml($_filter)) : ?>
        <?php echo $_html ?>
    <?php else : ?>
        <li>
            <a href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove"><?php echo $this->__('x') ?></a>
            <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> <?php echo $_filter->getMShowSelected() ? $this->__('not') : '' ?> <?php echo $this->stripTags($_filter->getLabel()) ?>
        </li>
    <?php endif; ?>
    <?php endforeach; ?>
    </ol>
    <?php endif; ?>
    <?php if (!Mage::helper('mana_core')->isMageVersionEqualOrGreater('1.7') && ($_parent = $this->getParentBlock()) /*&& $_parent->getShowInFilter() != 'above_products'*/) : ?>
    <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
    <?php endif; ?>
</div>
<?php endif; ?>
