<?php
$enableSlider = Mage::helper('zeon_attributemapping')
    ->getConfigData('front_scroller/active');

if ($enableSlider) :
    $_imagePath = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
    $scrollerdata = Mage::helper('zeon_attributemapping')->getCharactersListAll();
    $allUrl = Mage::helper('zeon_attributemapping')
        ->getConfigDetails('characterpage_url', 1);
    $urlSuffix = Mage::helper('zeon_attributemapping')
            ->getConfigDetails('url_prefix', 1);
            if ($urlSuffix) {
                $urlSuffix = '.'.$urlSuffix;
            }
    $allUrl = $allUrl.$urlSuffix;
    ?>

    <div id="attribute-slider">
        <div class="chter-right-bg"></div>
        <div class="chter-left-bg"></div>
        <ul>
        <?php
		$limit = Mage::helper('zeon_attributemapping')
            ->getConfigData('front_scroller/item_count');
        foreach ($scrollerdata as $key => $data) {
			$liClass = '';
			if ($key == 0) {
				$liClass = "class='first'";	
			}
			if ($key == $limit-1) {
				$liClass = "class='last'";	
			}
			 ?>
            <li <?php echo $liClass; ?>>
                <a title="" class="slider-option tooltip-active"
                href="<?php echo Mage::helper('zeon_attributemapping')->getAttributeUrl($data['option_id'], $data['request_path']); ?>"
                ><div class="show-tooltip" style="display:none"><div class="tip-arrow"></div><div class="tooltip-left"><div class="tooltip-middle"><?php echo $data['value'] ?></div></div></div>
                <img src="<?php echo $_imagePath.$data['slider_image']; ?>" />
                </a>

            </li>
        <?php } ?>
        </ul>

        <div class="attribute-slider-title">
            <a href="<?php echo $this->getUrl().$allUrl ?>" title="All Characters">
                <?php echo $this->__('&nbsp;'); ?>
            </a>
        </div>
    </div>

<?php endif; ?>
