<?php
// Get the best seller product collection.
$_productCollection = $this->getBestSellerProductCollection();
$_helper = $this->helper('catalog/output');

// Get the config setting.
$_configSettings = $this->helper('zeon_catalogmanager')->getConfigDetails('best_products');
$_maxCharLimit = (int) $_configSettings['char_limit'];
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                                        <?php $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        <?php echo ($_maxCharLimit > 0 && strlen($_productName) > $_maxCharLimit) ? substr($_productName, 0, $_maxCharLimit) . '...' : $_productName; ?>
                                    </a>
                                </h2>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>
                                <?php if (Mage::getStoreConfig('zeon_catalogmanager/best_products/general/price_visible')): ?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php endif; ?>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = 4; ?>
            <?php $i = 0;
            foreach ($_productCollection as $_product): ?>
                    <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid">
            <?php endif ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?> col-lg-3 col-sm-3 col-xs-6">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <h2 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                <?php echo ($_maxCharLimit > 0 && strlen($_productName) > $_maxCharLimit) ? substr($_productName, 0, $_maxCharLimit) . '...' : $_productName; ?>
                            </a>
                        </h2>
                        <?php if ($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>

                        <?php if (Mage::getStoreConfig('zeon_catalogmanager/best_products/price_visible')): ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <?php endif; ?>
                    </li>
                <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
        <span class="top-scroll" id="scroll-to-top-id">Top</span>
    </div>
<?php endif; ?>
<script type="text/javascript" charset="utf-8">
    jQuery(document).ready(function() {
        jQuery('.dropkick-select').dropkick();
    });
</script>
