<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>

<?php
$base_project =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
if (in_array('canApplyMsrp', get_class_methods(Mage::helper('catalog')))) {
    $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
} else {
    $canApplyMsrp = false;
}

$_product = Mage::getSingleton('catalog/product')->load($_item->getProduct()->getId());

if ($_product->getPersonalize()) {
    if (Mage::getSingleton('customer/session')->isLoggedIn()) {
        $customer = Mage::getSingleton('customer/session')->getCustomer()->getId();
    } else {
        $session = Mage::getSingleton("customer/session");
        $customer = $session->getEncryptedSessionId();
    }

    $personalizedData = Mage::getSingleton('personalize/personalize')->getPersonalizedInformation($_product->getId(), $customer);
}

$_shipsFrom = $_product->getShipsFrom();
$_shipsTo   = $_product->getShipsTo();
//Get Lead time of product.
$_leadTime = $_product->getLeadTime();

$_partyPlanerData = $_item->getBuyRequest()->getPartyplanner();
?>
<tr id="item-<?php echo $_item->getId(); ?>">
    <td class="first"><label class="label-show first">&nbsp;</label><?php if ($this->hasProductUrl() &&  ($_product->getSku()!= 'donate')): ?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><?php endif; ?><img src="<?php echo (isset($personalizedData) && !empty($personalizedData['thumbnail_paths'])) ? $personalizedData['thumbnail_paths'] : $this->getProductThumbnail()->resize(120); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" width="120" /><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></td>
    <td class="prod-info">
        <h2 class="product-name">
            <?php if ($this->hasProductUrl() &&  ($_product->getSku()!= 'donate')): ?>
                <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
            <?php else: ?>
                <?php echo $this->htmlEscape($this->getProductName()) ?>
            <?php endif; ?>
        </h2>
        <div class="sku"><?php echo $this->__('<strong>Item #</strong> %s', $_product->getSku()); ?></div>

        <?php if ($_options = $this->getOptionList()): ?>
            <dl class="item-options<?php echo ($_partyPlanerData) ? ' partyplanner-shopping' : ''; ?>">
                <?php if ($_partyPlanerData): ?>
                    <?php foreach ($_partyPlanerData as $_key => $_partyPlaner): ?>
                        <?php
                        if (in_array($_key, array('guest_count_hidden', 'childs_name_hidden', 'childs_age_hidden'))) {
                            continue;
                        } ?>
                        <span><strong><?php echo $_partyPlaner['label']; ?> :</strong> <?php echo $_partyPlaner['value']; ?></span>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php foreach ($_options as $_option) : ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <?php
                    $_optionLabel = strtoupper($_option['label']);
                    if ('IMAGE-FILE' == $_optionLabel):
                        continue;
                    endif;
                    ?>
                    <br />
                <span class="<?php echo isset($_option['print_value']) ? 'custom' : ''; ?>"><strong><?php echo isset($_option['print_value']) ? $this->htmlEscape($_optionLabel) : $this->htmlEscape($_option['label']); ?>: </strong></span>
                    <span><?php echo $_formatedOptionValue['value']; ?></span>
                <?php endforeach; ?>
                <?php if ($isVisibleProduct): ?>
                    &nbsp;&nbsp;<a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item parameters') ?>"><?php echo $this->__('edit') ?></a>
                <?php endif ?>
            </dl>
        <?php endif; ?>
        <?php if ($messages = $this->getMessages()): ?>
            <?php foreach ($messages as $message): ?>
                <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'] ?></p>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()): ?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>



    <?php if ($isVisibleProduct): ?>
    <!--    <a href="<?php /*echo $this->getConfigureUrl() */?>" title="<?php /*echo $this->__('Edit item parameters') */?>"><?php /*echo $this->__('Edit') */?></a>-->
    <?php endif ?>
    </td>


    <td class="a-left">
        <?php if ($_product->getIsInStock()): ?>
            <span><strong><?php echo $this->__('IN STOCK'); ?></strong></span>
            <?php if ($_product->getExpeditedShipping()): ?>
                <span><?php echo $this->__(Mage::getStoreConfig('expedited_setting/cart_settings/message')); ?></span>
            <?php else: ?>
				<?php if (!empty($_leadTime)): ?>
				<?php echo $this->__($_leadTime); ?>
				<?php endif; ?>
            <?php endif; ?>
        <?php else: ?>
            <span><strong><?php echo $this->__('OUT OF STOCK'); ?></strong></span>
        <?php endif; ?>
        <?php
            // For Showing the Drop Ship Note
           if ($_item->getProductType() == 'configurable') {
                $simpleProductId = $_item->getOptionByCode('simple_product')->getProduct()->getId();
                $simpleProduct = Mage::getModel('catalog/product')->load($simpleProductId);
               if ($simpleProduct->getData('drop_ship_item')) {
                   echo Mage::helper('dropshiping')->getDropShippingMessage();
               }
           } else {
                if ($_product->getData('drop_ship_item')) {
                   echo Mage::helper('dropshiping')->getDropShippingMessage();
                }
           }
       ?>
        <?php if (!empty($_shipsFrom)): ?>
            <span>
                <?php $days = (!empty($_shipsTo)) ? $_shipsFrom . ' to ' . $_shipsTo : $_shipsFrom; ?>
                <?php echo $this->__('Usually ships within %s Business Days', $days); ?>
            </span>
        <?php endif; ?>

				    <!-- My Code To Edit link of personalized product-->
    <?php $_product= Mage::getSingleton('catalog/product')->load($_item->getProductId()) ;
    //echo $_product->getResource()->getAttribute('attribute_code')->getFrontend()->getValue($_product);
    //echo $base_project;
    ?>

    <?php
    if (isset($personalizedData) && isset($personalizedData['design_id'])):
        $websiteId = Mage::getStoreConfig('personalize/mycustom_group/mycustom_field1');//Set the website id
        $includeScript = Mage::getStoreConfig('personalize/mycustom_group/mycustom_field');//Set the artifi include script

        echo $includeScript;
		?>
		<script>
		$.noConflict();
		// Code that uses other library's $ can follow here.
		</script>

    <?php
    /*
     // NO NEED TO DISPLAY THE EDIT LINK.
     </br> <a href="<?php echo $base_project; ?>personalize?id=<?php echo $_item->getProductId(); ?>&design_id=<?php echo $personalizedData['design_id'];?>&item_id=<?php echo $_item->getId() ?>&personalize_id=<?php echo $personalizedData['personalize_id'] ?>" title="<?php echo $this->__('Edit item parameters') ?>"><?php echo "Edit"; ?></a></br>
     */?>
        <!-- Code For Preview Link -->
        <br /><a href="javascript:void(0);" onclick="Artifi.PreviewPopUp('<?php echo $personalizedData['productcode'];?>', '<?php echo $websiteId; ?>' , '<?php echo $personalizedData['customer_id'];?>', true, 800, 600, '<?php echo $personalizedData['design_id'];?>', '');"><?php echo "Preview"; ?></a>
    <?php endif; ?>
    <!-- My Code Ends-->
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="a-left"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
        <label class="label-show">Price</label>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                </script>
            </span>
        </td>
    <?php else: ?>

        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <td class="a-left">
            <label class="label-show">Price</label>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                        <?php endif; ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                        <?php endif; ?>

                    </span>


                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
            </td>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <td><label class="label-show">Price</label>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                        <?php endif; ?>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedAmount()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
                        <?php endif; ?>

                    </span>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedAmount()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
            </td>
        <?php endif; ?>
    <?php endif; ?>

    <td class="a-center">
    <label class="label-show">Qty.</label>
    <div class="qty-box">
        <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" <?php if ($_product->getSku()== 'donate'):?>readonly='readonly'<?php endif;?>/>
        <button class="button white-button" title="<?php echo $this->__('Update'); ?>" type="submit"><span><span><?php echo $this->__('Update'); ?></span></span></button>
  	</div>
    <div class="wishlist-item">
        <hr>
        <?php if ($this->helper('wishlist')->isAllowInCart()): ?>
        <a class="remove-proitem" href="javascript:void(0);" onclick="if (confirm('<?php echo $this->__('Do you really want to remove this item from cart?'); ?>')) {ajaxCart.remove('<?php echo $this->getDeleteUrl() ?>', <?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/cart_enabled') ? 'true' : 'false'; ?>);}" title="<?php echo $this->__('remove item'); ?>"><?php echo $this->__('remove item'); ?></a>
            <?php if ($isVisibleProduct): ?>
                
                <input type="hidden" value="0" class="wishlist-item" id="wishlist_<?php echo $_item->getId() ?>" name="cart[<?php echo $_item->getId() ?>][wishlist]" />
                <a class="move-to-wishlist link-wishlist use-ajax" id="movelist-id-<?php echo $_item->getId() ?>" href="javascript:void(0);" onclick="moveToWishlist('<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>', this);" title="<?php echo $this->__('move to wishlist'); ?>"><?php echo $this->__('move to wishlist'); ?></a>
            <?php endif ?>
        <?php endif; ?>
        </div>
    </td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="a-left"><label class="label-show">Total</label>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                    <?php endif; ?>

                    <?php if ($canApplyMsrp): ?>
                        <span class="cart-msrp-subtotal">--</span>
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                        <?php endif; ?>
                    <?php endif; ?>

                </span>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
        </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td><label class="label-show">Total</label>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                    <?php endif; ?>

                    <?php if ($canApplyMsrp): ?>
                        <span class="cart-msrp-subtotal">--</span>
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedRowAmount()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxRowDisposition()) ?>
                        <?php endif; ?>
                    <?php endif; ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedRowAmount()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
        </td>
    <?php endif; ?>   
        <td class="a-center">
		
		 <?php
			if (Mage::app()->getStore()->isCurrentlySecure()) {
				$deletUrl = str_replace('http://', 'https://', $this->getDeleteUrl());			
		?>
            <a class="remove-item" href="javascript:void(0);" onclick="if (confirm('<?php echo $this->__('Do you really want to remove this item from cart?'); ?>')) {ajaxCart.remove('<?php echo $deletUrl; ?>', <?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/cart_enabled') ? 'true' : 'false'; ?>);}" title="<?php echo $this->__('remove item'); ?>"><?php echo $this->__('X'); ?></a>
			<?php } else {?>
			 <a class="remove-item" href="javascript:void(0);" onclick="if (confirm('<?php echo $this->__('Do you really want to remove this item from cart?'); ?>')) {ajaxCart.remove('<?php echo $this->getDeleteUrl(); ?>', <?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/cart_enabled') ? 'true' : 'false'; ?>);}" title="<?php echo $this->__('remove item'); ?>"><?php echo $this->__('X'); ?></a>
			<?php } ?>	
			
        </td>
</tr>