<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>

<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div id="block-wishlist" class="block block-wishlist">
        <div class="block-title">
            <strong><span><?php echo $this->__('My Wishlist <small>(%d)</small>', $this->getItemCount()) ?></span></strong>
        </div>
        <div class="block-content">
            <p class="block-subtitle"><?php echo $this->__('Last Added Items') ?></p>
            <?php if ($this->hasWishlistItems()): ?>
                <ol class="mini-products-list" id="wishlist-sidebar">
                    <?php foreach ($this->getWishlistItems() as $_item): ?>
                        <?php $product = $_item->getProduct(); ?>
                        <li class="item">
                            <a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a>
                            <div class="product-details">
                                <a href="<?php echo $this->getItemRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the wishlist?') ?>');" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
                                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></p>
                                <?php echo $this->getPriceHtml($product, false, '-wishlist') ?>
                                <?php if ($product->isSaleable() && $product->isVisibleInSiteVisibility()): ?>
                                    <a href="javascript:void(0);" onclick="<?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/whishlist_enabled') ? 'addWItemToCart(' . $_item->getId() . ');' : 'setLocation("' . $this->getItemAddToCartUrl($_item) . '");'; ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                                <?php endif; ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
                <script type="text/javascript">
                    decorateList('wishlist-sidebar');
                    function addWItemToCart(itemId) {
                        var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
                        url = url.gsub('%item%', itemId);
                        url = url.gsub('wishlist/index/cart', 'ajaxcart/wishlist/cart');
                        ajaxCart.addWishListItemsToCart(url)
                    }
                </script>
                <div class="actions">
                    <a href="<?php echo $this->helper('wishlist')->getListUrl() ?>"><?php echo $this->__('Go to Wishlist') ?></a>
                </div>
            <?php else: ?>
                <p class="empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
            <?php endif ?>
        </div>
    </div>
    <?php

 endif ?>
