<div class="green-title-sec">
    <span class="green-title"><?php echo $this->__('Track Your Order'); ?></span>
</div>

<form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
    <div class="fieldset track-your-order col-lg-9 col-md-9 col-sm-9 col-xs-12">
     <p class="required"><?php echo Mage::helper('sales')->__('* required') ?></p>
<!--        <h2 class="legend"><?php //echo Mage::helper('sales')->__('Order Information') ?></h2>-->

        <ul class="form-list">
           <li>
               <label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" />
               </div>
           </li>
           <li class="wide">
               <div class="email-billing">
                   <span><?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.</span>
                </div>
           </li>
           <li>
                <label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  />
               </div>
           </li>
           <li>
               <label class="required"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
               
               <div class="input-box">
                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email">Email Address</option>
                       <option value="zip">ZIP Code</option>
                   </select>
               </div>
           </li>
           <li id="oar-email">
                   <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
               <div class="input-box">
                   <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"  />
               </div>
           </li>
           <li id="oar-zip" style="display:none;">
               <label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" />
               </div>
           </li>
       </ul>
    </div>
    <div class="buttons-set  col-lg-9 col-md-9 col-sm-9 col-xs-12">
        <button type="submit" title="<?php echo Mage::helper('sales')->__('Continue') ?>" class="button red-button"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
jQuery(document).ready(function(){
    jQuery('#quick_search_type_id').dropkick();
});
</script>
