<?php
/**
 * Zeon Solutions
 * Catalog Module
 * The Catalog module has been overridden.
 * refer the text file for details.
 *
 * @category   Zeon
 * @package    Zeon_Catalog
 * @copyright  Copyright (c) 2008 Zeon Solutions (http://www.zeonsolutions.com/)
 * @version    1.01
 * @date       jan 29 2009 1846 IST
 */
?>
<?php
/**
 * Category list toolbar
 *
 * @see Zeon_Catalog_Block_Category_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <table class="pager" cellspacing="0">
        <tr>
            <td>
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
            </td>
            <?php if($this->getLastPageNum()>1): ?>
            <td class="pages">
                <strong><?php echo $this->__('Page:') ?></strong>
                <ol>
                <?php if (!$this->isFirstPage()): ?>
                    <li><a href="<?php echo $this->getPreviousPageUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>" alt="<?php echo $this->__('Previous') ?>" /></a></li>
                <?php endif ?>
                <?php foreach ($this->getPages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <li><span class="on"><?php echo $_page ?></span></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                    <?php endif ?>
                <?php endforeach;; ?>
                <?php if (!$this->isLastPage()): ?>
                    <li><a href="<?php echo $this->getNextPageUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>" alt="<?php echo $this->__('Next') ?>" /></a></li>
                <?php endif ?>
                </ol>
            </td>
            <?php endif; ?>
            <td class="a-right">
                <?php echo $this->__('Show') ?> <select onchange="setLocation(this.value)">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select> <?php echo $this->__('per page') ?>
            </td>
        </tr>
    </table>
    <?php if( $this->isExpanded() ): ?>
    <table class="view-by" cellspacing="0">
        <tr>
            <?php if( $this->isEnabledViewSwitcher() ): ?>
            <td>
                <?php $_modes = $this->getModes(); ?>
                <?php if($_modes && count($_modes)>1): ?>
                <?php echo $this->__('View as') ?>:
                <?php foreach ($this->getModes() as $_code=>$_label): ?>
                    <?php if($this->isModeActive($_code)): ?>
                        <strong><?php echo $_label ?></strong>&nbsp;
                    <?php else: ?>
                        <a href="<?php echo $this->getModeUrl($_code) ?>"><?php echo $_label ?></a>&nbsp;
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php endif; ?>
            </td>
            <?php endif; ?>
            <td class="sort-by">

            </td>
        </tr>
    </table>
    <?php endif; ?>
<?php endif ?>
<br/><br/>
<?php
//echo '*****';
echo $this->getChildHtml('right.reports.product.viewed');
?>
