<?php
/**
 * zeonsolutions inc.
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $productType = $_product->getTypeID(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php
//$personalize_value =  Mage::getModel('catalog/product')->load($_product->getId())->getPersonalize();
$isPersonalized =  $_product->getPersonalize();
if ($isPersonalized == '1') {
    $buttonTitle = $this->__('Personalize');
}
$customer = Mage::getSingleton('customer/session')->getCustomer();
$email=$customer->getEmail();
?>
    <div class="add-to-cart">
        <!--  Quantity testbox and label -->
        <?php if (!$_product->isGrouped() && $productType != 'bundle'): ?>
            <div class="qty-box">
                <label for="qty"><?php echo $this->__('Quantity') ?></label>
                <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->escapeHtml($this->getProductDefaultQty() * 1) ?>" title="<?php echo $this->__('Quantity') ?>" <?php if (!$_product->isSaleable()) { echo 'disabled'; } ?> class="input-text qty" />
            </div>
        <?php endif; ?>
        <!--  out of stock label -->

            <?php if ($this->displayProductStockStatus()): ?>
                <?php if (!$_product->isAvailable()): ?>
                     <div class="item-oos"><p class="availability out-of-stock"><?php echo $this->__('Item out of stock') ?></p></div>
                     <div class="cart-btn-set">
                <?php else: ?>

                <?php endif; ?>
            <?php endif; ?>
        <?php $_options = $_product->getOptions();?>
        <!--  confirmation checkbox -->
        <?php if ($_product->isSaleable()): ?>
        <?php if (count($_options)):?>
        <?php if ($this->hasOptions() && $isPersonalized != 1) : ?>
            <div class="required-box">
                <span class="review-approval"><?php echo $this->__('Review & Approval') ?></span>
                <input type="checkbox" name="required_check" />
                <span class="note"><?php echo $this->__('I confirm the personalization indicated above is correct.') ?></span>
            </div>
        <?php endif; ?>
        <?php endif; ?>
        <!-- "Add To Cart" button -->
        <?php
        $classToAdd = "";
        if ($productType == 'bundle') {
            $classToAdd = "hide";
        } ?>
        <div class="cart-btn-set">
            <?php if ($isPersonalized != 1): ?>
            <div id="cart-button-div-id" class="cart-button <?php echo $classToAdd; ?>">
                <button type="submit" title="<?php echo $buttonTitle ?>" class="button btn-cart red-button"><span><span> <?php echo $buttonTitle; ?></span></span></button>
                <?php echo $this->getChildHtml('', true, true) ?>
            </div>
            <?php endif; ?>
        <?php endif; ?>
        <!-- Email stock link -->
        <?php echo $this->getChildHtml('alert_urls') ?>
        <!-- wishlist link -->
        <?php
        if ($productType != 'bundle') { ?>
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <div class="add-wishlist">
                <span class="add-wish-icon" onclick="<?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/whishlist_enabled') ? "ajaxCart.addUpdate('ajaxcart/wishlist/add', this)" : "productAddToCartForm.submitLight(this, '$_wishlistSubmitUrl')"; ?>; return false;"></span>
                    <a href="javascript:void(0);" onclick="<?php echo Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/whishlist_enabled') ? "ajaxCart.addUpdate('ajaxcart/wishlist/add', this)" : "productAddToCartForm.submitLight(this, '$_wishlistSubmitUrl')"; ?>; return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                </div>
                <input type="hidden" name="id" id="wishlist_item_id" value="<?php echo $this->getRequest()->getParam('id') ?>" />
                <input type="hidden" name="wishlist_id" id="wishlist_id" value="0" />
            <?php endif; ?>
        <?php
        } ?>
        </div>
    </div>
<script>
    jQuery(document).ready(function() {
        validatePersonalizedFields();
    });
</script>
<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
<script type="text/javascript">
var deviceType =
/Mobile|iP(hone|od)|Android|BlackBerry|IEMobile|Silk/.test(navigator.userAgent)
? "m" : /iPad/.test(navigator.userAgent) ? "t" : "d";
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
{ event: "setAccount", account: 11065},
{ event: "setSiteType", type: deviceType},
{ event: "setEmail", email: "<?php echo $email;?>"},
{ event: "viewItem", product: "<?php echo $_product->getSku();?>" });
</script>