<?php
/**
 * zeonsolutions inc.
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $productType = $_product->getTypeID(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php
//$personalize_value =  Mage::getModel('catalog/product')->load($_product->getId())->getPersonalize();
$isPersonalized =  $_product->getPersonalize();
if ($isPersonalized == '1') {
    $buttonTitle = $this->__('Personalize');
}
$email='';
$customer = Mage::getSingleton('customer/session')->getCustomer();
$email=$customer->getEmail();
?>
    <div class="add-to-cart">
        <!--  Quantity testbox and label -->
        <?php if (!$_product->isGrouped() && $productType != 'bundle'): ?>
            <div class="qty-box">
                <label for="qty"><?php echo $this->__('Quantity') ?></label>
                <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->escapeHtml($this->getProductDefaultQty() * 1) ?>" title="<?php echo $this->__('Quantity') ?>" <?php if (!$_product->isSaleable()) { echo 'disabled'; } ?> class="input-text qty" />
            </div>
        <?php endif; ?>
        <!--  out of stock label -->

            <?php if ($this->displayProductStockStatus()): ?>
                <?php if (!$_product->isAvailable()): ?>
                     <div class="item-oos"><p class="availability out-of-stock"><?php echo $this->__('Item out of stock') ?></p></div>
                     <div class="cart-btn-set">
                <?php else: ?>

                <?php endif; ?>
            <?php endif; ?>
        <?php $_options = $_product->getOptions();?>
        <!--  confirmation checkbox -->
        <?php if ($_product->isSaleable()): ?>
        <?php if (count($_options)):?>
        <?php if ($this->hasOptions() && $isPersonalized != 1) : ?>
            <div class="required-box">
                <span class="review-approval"><?php echo $this->__('Review & Approval') ?></span>
                <input type="checkbox" name="required_check" />
                <span class="note"><?php echo $this->__('I confirm the personalization indicated above is correct.') ?></span>
            </div>
        <?php endif; ?>
        <?php endif; ?>
        <!-- "Add To Cart" button -->
        <?php
        $classToAdd = "";
        if ($productType == 'bundle') {
            $classToAdd = "hide";
        } ?>
        <div class="cart-btn-set">
            <?php if ($isPersonalized != 1): ?>
            <div id="cart-button-div-id" class="cart-button <?php echo $classToAdd; ?>">
                <button type="submit" title="<?php echo $buttonTitle ?>" class="btn-cart red-button  btn btn-primary"><span><span> <?php echo $buttonTitle; ?></span></span></button>
                <?php echo $this->getChildHtml('', true, true) ?>
            </div>
            <?php endif; ?>
        <?php endif; ?>
        
        </div>
    </div>
<script>
    jQuery(document).ready(function() {
        validatePersonalizedFields();
    });
</script>
<style>
   .btn-primary, .btn-primary:hover, .btn-primary:focus, .btn-primary:visited {
    color: #fff;
}

.btn {
    border-radius: 4px;
}
.btn, .btn:hover, .btn:focus, .btn:visited {
    color: #fff;
    outline: 0 none;
}
.btn {
    background-color: #007dc6;
    border: 0 none;
    display: inline-block;
    font-size: 16px;
    font-weight: 600;
    line-height: 1;
    padding: 12px 34px;
    text-align: center;
    vertical-align: middle;
}
.btn-primary, .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
    background-color: #f47421;
}
</style>