<?php
/* @var $this Gene_Braintree_Block_Creditcard */
$_code = $this->getMethodCode()
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;" class="form-list">

    <?php echo $this->getSavedChildHtml(); ?>

    <div id="credit-card-form"<?php echo ($this->hasSavedDetails() && $this->getMethod()->isVaultEnabled() ? ' style="display: none;"' : ''); ?>>
        <ul class="form-list">

            <?php if($this->showAcceptedCards()): ?>
                <li id="braintree-accepted-cards">
                    <label for="<?php echo $_code ?>_cc_number">
                        <?php echo $this->__('We Accept'); ?>
                        <div>
                            <?php foreach($this->getAllowedCards() as $card): ?>
                                <img src="<?php echo $this->getSkinUrl('images/gene/braintree/' . $card['value'] . '.png') ?>" alt="<?php echo $card['label']; ?>" />
                            <?php endforeach; ?>
                        </div>
                    </label>
                </li>
            <?php endif; ?>

            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box card-number">
                    <input type="tel" data-genebraintree-name="number" name="payment[cc_number]" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type validate-accepted-type" autocomplete="cc-number" />

                    <div class="card-type"><img src="<?php echo $this->getSkinUrl('images/gene/braintree/card.png') ?>" id="card-type-image" /></div>
                </div>
            </li>
            <li id="<?php echo $_code ?>_cc_type_exp_div">
                <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" data-genebraintree-name="expiration_month" class="month validate-cc-exp required-entry">
                            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" data-genebraintree-name="expiration_year" class="year required-entry">
                            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <?php echo $this->getChildHtml() ?>
            <?php if($this->hasVerification()): ?>
                <li id="<?php echo $_code ?>_cc_type_cvv_div">
                    <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" data-genebraintree-name="cvv" autocomplete="off" />
                        </div>
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </li>
            <?php endif; ?>

            <?php if ($this->canSaveCard()): ?>
                <li id="<?php echo $_code ?>_store_in_vault_div">
                    <input type="checkbox" title="<?php echo $this->__('Save this card for future use') ?>"
                           class="input-checkbox" id="<?php echo $_code ?>_store_in_vault" name="payment[save_card]"
                           value="1"/>
                    <label for="<?php echo $_code ?>_store_in_vault" style="float:none;"><?php echo $this->__(
                            'Save this card for future use'
                        ) ?></label>
                </li>
            <?php endif; ?>

        </ul>

        <!-- Fields for the payment method -->
        <input type="hidden" name="payment[payment_method_nonce]" id="creditcard-payment-nonce" />

        <input type="hidden" id="<?php echo $_code ?>_cc_type" />
    </div>

</div>

<style type="text/css">
    .card-number {
        position: relative;
    }

    .card-type {
        position: absolute;
        top: 0;
        left: 6px;
    }

    .card-number input {
        height: 46px!important;
        text-indent: 56px!important;
    }
</style>

<script type="text/javascript">
    //<![CDATA[
    Validation.creditCartTypes = $H({
        'VI': [new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true],
        'MC': [new RegExp('^5[1-5][0-9]{14}$'), new RegExp('^[0-9]{3}$'), true],
        'AE': [new RegExp('^3[47][0-9]{13}$'), new RegExp('^[0-9]{4}$'), true],
        'DI': [new RegExp('^6011[0-9]{12}$'), new RegExp('^[0-9]{3}$'), true],
        'JCB': [new RegExp('^(3[0-9]{15}|(2131|1800)[0-9]{11})$'), new RegExp('^[0-9]{4}$'), true],
        'OT': [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false],
        'ME': [new RegExp('^(?:5[0678][0-9]{2}|6304|6390|67[0-9]{2})[0-9]{8,15}$'), new RegExp('^[0-9]{3}$'), true]
    });
    //]]>
</script>

<!-- Attach an event onto all radio buttons -->
<script type="text/javascript">

    // Set a flag to determine whether the PayPal flag is initialized
    var CreditCardInit = false;

    // Wrap our logic in a function so we can init in different ways
    initCreditCard = function() {

        // Verify that vzero is defined before attempting to use it
        if (typeof vzero !== 'undefined') {

            // Tell the system we're init
            CreditCardInit = true;

            // Always set the amount as it's needed within 3D secure requests
            vzero.setAmount('<?php echo Mage::helper('gene_braintree')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->collectTotals()->getGrandTotal()); ?>');

            // We now need to set this information into the browser
            vzero.setBillingName("<?php echo $this->jsQuoteEscape(Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress()->getName(), '"'); ?>");
            vzero.setBillingPostcode("<?php echo $this->jsQuoteEscape(Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress()->getPostcode(), '"'); ?>");

            // Set the accepted cards
            vzero.setAcceptedCards(<?php echo $this->getCcAvailableTypes(); ?>);

            <?php
            // Dynamically swap the 3Ds flag in the JS class
            if($this->getMethod()->is3DEnabled()): ?>
                vzero.setThreeDSecure(true);
            <?php else: ?>
                vzero.setThreeDSecure(false);
            <?php endif; ?>
        }

        // Observe the card type
        if(typeof vzero !== "undefined") {
            vzero.observeCardType();
            vzero.creditCardLoaded();
        }

    };

    // Load up credit card
    initCreditCard();

    // If the function didn't run on the load of the payment method do it on dom:loaded
    if(!CreditCardInit) {
        document.observe('dom:loaded', function () {
            initCreditCard();
        });
    }

    // Add our new validation type
    Validation.add('validate-accepted-type', 'Sadly, we\'re unable to accept this type of card, please try another.', function(v) {
        if($('<?php echo $_code ?>_cc_type') != undefined) {
            if (vzero.getAcceptedCards().indexOf($('<?php echo $_code ?>_cc_type').value) == -1) {
                return false;
            }
        }
        return true;
    });

    // Update a couple of the messages
    if(Validation.get('validate-cc-type') != undefined) {
        Validation.get('validate-cc-type').error = "<?php echo $this->__('We cannot detect the card type for this card number, please try re-entering your card details.'); ?>";
    }
    if(Validation.get('validate-cc-number') != undefined) {
        Validation.get('validate-cc-number').error = "<?php echo $this->__('We cannot match this card number to any of our accepted payment methods, please try re-entering your details.'); ?>"
    }
</script>