<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
?>
<?php
/* @var $this Mage_Bundle_Block_Catalog_Product_View */
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div id="bundle-product-wrapper">
    <div id="bundleProduct">
        <div id="productView" class="product-view" style="width: 800px;">
            <div class="product-essential">
                <div class="product-shop">
                    <div class="product-main-info">
                        <div class="product-name">
                            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                        </div>
                        <p class="product-ids"><?php echo $this->__('SKU#%s', $this->htmlEscape($_product->getSku())); ?></p>
                        <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php echo $this->getChildHtml('alert_urls') ?>
                    </div>
                    <?php echo $this->getChildHtml('tierprices') ?>
                    <?php echo $this->getChildHtml('customize_button') ?>
                    <?php if (!$this->hasOptions()): ?>
                        <?php if ($_product->isSaleable()): ?>
                            <div>
                                <button type="button" onclick="window.location='<?php echo Mage::getBaseUrl() . $_product->getRequestPath(); ?>?startcustomization=1'" class="button btn-cart"><span><span><?php echo $this->__("Customize and Add to Cart") ?></span></span></button>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>

                    <?php if ($_product->getShortDescription()): ?>
                        <div class="short-description std">
                            <h2><?php echo $this->__('Quick Overview') ?></h2>
                            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                        </div>
                    <?php endif; ?>

                    <?php echo $this->getChildHtml('other'); ?>

                </div>
                <div class="product-img-box">
                    <?php echo $this->getChildHtml('media') ?>
                </div>
            </div>
            <div class="product-collateral">
                <?php $_description = $this->getChildHtml('description') ?>
                <?php $_additional = $this->getChildHtml('additional') ?>
                <?php if ($_description || $_additional): ?>
                    <dl id="collateral-tabs" class="collateral-tabs">
                        <?php if ($_description): ?>
                            <dt class="tab"><span><?php echo $this->__('Details') ?></span></dt>
                            <dd class="tab-container">
                                <div class="tab-content"><?php echo $_description ?></div>
                            </dd>
                        <?php endif; ?>
                        <?php if ($_additional): ?>
                            <dt class="tab"><span><?php echo $this->__('Additional Information') ?></span></dt>
                            <dd class="tab-container">
                                <div class="tab-content"><?php echo $_additional ?></div>
                            </dd>
                        <?php endif; ?>
                    </dl>
                    <script type="text/javascript">new Enterprise.Tabs('collateral-tabs')</script>
                <?php endif; ?>
                <?php if ($this->canEmailToFriend()): ?>
                    <p class="emailto-link"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>
            </div>
            <div class="clearer"></div>
            <?php echo $this->getChildHtml('relatedProducts') ?>
            <?php echo $this->getChildHtml('upsell_products') ?>
            <?php echo $this->getChildHtml('productTagList') ?>
            <?php echo $this->getChildHtml('product_additional_data') ?>
        </div>
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" <?php if (Mage::getStoreConfigFlag('zeon_ajaxcart/frontend/cart_enabled')) { ?> onsubmit="ajaxCart.addUpdate('ajaxcart/cart/add');return false;" <?php } ?> id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                <div id="options-container" style="display: block;">
                    <div id="customizeTitle" class="page-title title-buttons">
                        <h1><?php echo $this->__('Party Planner!') ?></h1>
                        <br /><br />
                        <h3 class="left"><?php echo $this->__('Give us the details and PRESTO - we\'ll help you plan the perfect party!'); ?></h3>
                        <div class="left">
                            <span class="left">1)</span>
                            <ul id="guestInfo" class="left">
                                <li class="gstCt">
                                    <span class="ars-hide"><?php echo $this->__('Enter Number of Guests'); ?></span>
                                    <input type="hidden" value="<?php echo $this->__('Number of Guests'); ?>" name="partyplanner[guest_count][label]">
                                    <input type="text" maxlength="3" id="guest_count" name="partyplanner[guest_count][value]">
                                </li>
                                <li class="chldsNm">
                                    <span class="ars-hide"><?php echo $this->__('Enter Your Child\'s Name'); ?></span>
                                    <input type="hidden" value="<?php echo $this->__('Child\'s Name'); ?>" name="partyplanner[childs_name][label]">
                                    <input type="text" maxlength="9" id="childs_name" name="partyplanner[childs_name][value]">
                                </li>
                                <li class="chldsAg">
                                    <span class="ars-hide"><?php echo $this->__('Enter Their Age'); ?></span>
                                    <input type="hidden" value="<?php echo $this->__('Age'); ?>" name="partyplanner[childs_age][label]">
                                    <input type="text" maxlength="2" id="childs_age" name="partyplanner[childs_age][value]">
                                </li>
                                <li class="goButton">
                                    <a class="goBtn" href="#go"><span>Go</span></a>
                                </li>
                            </ul>
                        </div>

                        <a href="#" onclick="Enterprise.Bundle.end(); return false;"><small>&lsaquo;</small> Go back to product detail</a>
                    </div>
                    <?php echo $this->getChildHtml('bundleSummary') ?>
                    <?php if ($this->getChildChildHtml('container1')): ?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php elseif ($this->getChildChildHtml('container2')): ?>
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>
<script type="text/javascript">
<?php if ($this->isStartCustomization()): ?>
        Enterprise.Bundle.start();
<?php endif; ?>
var productAddToCartForm = new VarienForm('product_addtocart_form');
productAddToCartForm.submit = function(button, url) {
    if (this.validator.validate()) {
        var form = this.form;
        var oldUrl = form.action;

        if (url) {
            form.action = url;
        }
        var e = null;
        try {
            this.form.submit();
        } catch (e) {
        }
        this.form.action = oldUrl;
        if (e) {
            throw e;
        }

        if (button && button != 'undefined') {
            button.disabled = true;
        }
    }
}.bind(productAddToCartForm);

productAddToCartForm.submitLight = function(button, url){
    if(this.validator) {
        var nv = Validation.methods;
        delete Validation.methods['required-entry'];
        delete Validation.methods['validate-one-required'];
        delete Validation.methods['validate-one-required-by-name'];
        if (this.validator.validate()) {
            if (url) {
                this.form.action = url;
            }
            this.form.submit();
        }
        Object.extend(Validation.methods, nv);
    }
}.bind(productAddToCartForm);

// Initialize and start the bundle process.
Enterprise.Bundle.initialize();
//Enterprise.Bundle.start();
</script>
