<?php
/**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.zeonsolutions.com/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    enterprise_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://shop.zeonsolutions.com/license-enterprise.txt
 */
$helper = Mage::helper('zeon_googletagmanager');
if ($helper->isEnabled()) {
    ?>
    <!-- Google Tag Manager -->
    <?php
    echo $this->_getDataLayer();
    $containerId = $helper->getContainerId();
    $dataLayerName = $helper->getDataLayerName();
    $isSecure = Mage::app()->getFrontController()->getRequest()->isSecure();
    ?>
    <noscript>
    <iframe src="<?php echo ($isSecure) ? 'https://' : 'http://'; ?>www.googletagmanager.com/ns.html?id=<?php echo $containerId; ?>"
            height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\">
    </iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='<?php echo $dataLayerName; ?>'?'&l='+l:'';j.async=true;j.src=
                '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','<?php echo $dataLayerName; ?>','<?php echo $containerId; ?>');        
    </script>
    <!-- End Google Tag Manager -->
<?php } ?>