<?php
/**
 * Zeon
 * Manufacturer list all module
 *
 * @category   Zeon
 * @package    Zeon_Manufacturer
 * @copyright  Copyright (c) 2008 Zeon Solutions.
 * @license    http://www.opensource.org/licenses/gpl-3.0.html GNU General Public License version 3
 */
?>
<?php
/**
 * Attribute List All
 *
 * @see Zeon_Attributemapping_Block_View
 */
?>
<div class="category-view">
<?php $_attributeList = $this->getAttributeList();
$attributeData = $this->getAttributeData();
$configCatPerRow = $this->getConfigDetails('category_list/category_grid_per_row');
$_collectionSize = count($_attributeList);
$_imageUrl = Mage::getBaseUrl('media');
$helper = Mage::helper('zeon_attributemapping');
?>
<?php if($_collectionSize < 1): ?>
    <div class="note-msg">
        <?php echo $this->__('There are no %s matching the selection.', $attributeData->getFrontendLabel()) ?>
    </div>
<?php else: ?>
<div class="category-products attribute-list">
    <?php
    // Set the page limit.
    $configCatPerRow = Mage::getStoreConfig('catalog/category_list/category_grid_per_row'); ?>
    <?php $i=0; foreach ($_attributeList as $attribute): ?>
        <?php
        $_logoUrl = $_imageUrl.$attribute['logo_image'];
        if ($attribute['logo_image'] == '') {
            $_logoUrl = $this->getSkinUrl('images/no_image_c.jpg');
        }
        $attributeUrl = $helper->getAttributeUrl($attribute['option_id'], $attribute['request_path']);
        ?>

        <?php if(($i++ % $configCatPerRow) == 0): ?>
            <ul class="products-grid <?php if ($i == 1): ?> first<?php elseif (($i+1) == $_collectionSize): ?> last<?php endif;?>">
        <?php endif; ?>
            <li class="item<?php if (($i - 1) % $configCatPerRow == 0): ?> first<?php elseif ($i % $configCatPerRow == 0): ?> last<?php endif; ?> col-lg-3 col-sm-3 col-xs-6">
                <h2 class="category-name">
                    <a href="<?php echo $attributeUrl ?>" onclick="setLocation('<?php echo $attributeUrl ?>');" title="<?php echo $this->htmlEscape($attribute['value']) ?>"><?php echo $this->htmlEscape($attribute['value']) ?></a>
                </h2>
                <a class="category-img" href="<?php echo $attributeUrl ?>" onclick="setLocation('<?php echo $attributeUrl ?>');" title="<?php echo $this->htmlEscape($attribute['value']) ?>">
                        <img src="<?php echo $_logoUrl; ?>" alt="<?php echo $this->htmlEscape($attribute['value']) ?>" />
                    </a>
            </li>
        <?php if( ($i % $configCatPerRow) == 0 || $i==$_collectionSize): ?>
            </ul>
        <?php endif; ?>

    <?php endforeach ?>
</div>
<?php endif; ?>
</div>